### ISSUE TITLE
Proposal: Migration to Webpack

### ISSUE THREAD

**Issue by gvarandas** [okfn-brasil/perfil-politico-frontend#12]
Considering that the project is using Gulp as its bundler/task automator, why not using webpack or parcel as a bundler?
That should require much less configuration to achieve the same results and open a whole new set of features (as bundle splitting in a near future).
I'd be willing to test this proposal and present the results here. 🤖

**Comment by cuducos** [comment]
I like the idea. Go for it if you wish : )

**Comment by cuducos** [comment]
Closed by #18
