### ISSUE TITLE
Change state information title when filtering by president

### ISSUE THREAD

**Issue by gvarandas** [okfn-brasil/perfil-politico-frontend#20]
# Problem
Currently, whenever you filter any group by state, the information is shown accurately.
But the state is meaningless when you're filtering by the **president** position (since it has a national reach).

<img width="946" alt="issue president" src="https://user-images.githubusercontent.com/5504958/46539615-5feb4c00-c88d-11e8-9b42-57fa6cd6e8d7.png">

# Solution Proposal
To change the presented title

**from**
> São 13 candidatos a presidente em São Paulo

**to**

> São 13 candidatos a presidente no Brasil

**Comment by gvarandas** [comment]
This might be a good first issue for someone to engage with the project 🤖

**Comment by MVictorM** [comment]
can I take this?

**Comment by cuducos** [comment]
> can I take this?

Make youserlf at home <3

**Comment by cuducos** [comment]
Closed by #23
