### ISSUE TITLE
Use HTML template engine

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/perfil-politico-frontend#21]
We have repeated snippets of code in our three HTML pages (`index.html`, `sobre.html` and `faq.html`). The DRY philosophy invites use _includes_ to avoid this repetition and enhance maintainability.

**Comment by siddhant-soni** [comment]
hey, I would like to take this up

**Comment by cuducos** [comment]
> hey, I would like to take this up

Go for it ; ) The idea is to avoid repetition such as #22

**Comment by siddhant-soni** [comment]
Alright! Is there a particular engine that you want to use?

**Comment by cuducos** [comment]
No, nothing specific in mind.

**Comment by guidiego** [comment]
If I could suggest: Handlebars is a nice pick for it! We can do many kinds of helpers in this project :D

**Comment by siddhant-soni** [comment]
@guidiego thanks for the suggestion, I'll have a look

**Comment by gvarandas** [comment]
Also, [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) works very well with HTML templates.
I'd recommend to check it out for integration with the build process.

**Comment by siddhant-soni** [comment]
@gvarandas Thank you for the suggestion, but I have already done it with Handlebars. Please have a look, I would appreciate any feedback.
