### ISSUE TITLE
Add Linter

### ISSUE THREAD

**Issue by caian-gums** [okfn-brasil/perfil-politico-frontend#3]
Hey, I've noticed that the project doesn't have a `linter`. Is it a valid proposal to help with this?

**Comment by caian-gums** [comment]
I can fork the project and place a linter with some basic stuff. I think I can do this on this week before Friday and open the PR.

Is there any template for PR or minimal description that I have to do?

**Comment by cuducos** [comment]
No template so far. I think the best idea is not only to adopt a linter, but to make sure a CI checks for it and blocks new code to be added if it doesn't respect the linter coding style. I'm not into the JS world but we implemented this scheme in the backend using Black in the CI, so I leave this as a possible reference: https://github.com/okfn-brasil/perfil-politico/pull/54

**Comment by caian-gums** [comment]
I'm familiar with [eslint](https://eslint.org/). I'll try to place a CI too and if possible something like a pre-hook(e.g. [husky](https://github.com/typicode/husky)) for this kind of preventing the code being committed/pushed without validating.

I can open the PR and make it in parts so you can check for possible changes or better approaches.

**Comment by gvarandas** [comment]
Is this solved yet?
I could contribute with a simple eslint/husky integration that should work out of the box.

**Comment by cuducos** [comment]
> Is this solved yet?

Not yet, but maybe @caian-gums is working on it. You might want to check with them.

> I could contribute with a simple eslint/husky integration that should work out of the box.

Sounds good. I think a pre-commit hook would be great (but optional). Essentially what we need as a first-step is a CI check to throw us a red light when code is not formatted properly ; )

**Comment by cuducos** [comment]
> in my experimentations I also added prettier as a code formatter

Just googled it and… _opinionated code formatter_. Love it : )

**Comment by cuducos** [comment]
Closed by #13
