### ISSUE TITLE
[Ideação] Mapeamento de dados

### ISSUE THREAD

**Issue by giuliocc** [okfn-brasil/perfil-politico-frontend#44]
O mapeamento de dados sobre os candidatos é de suma importância quando tratamos da visualização das mesmas. Por isso será feito um mapeamento de quais dados estão disponíveis em nossas bases de dados, sendo utilizadas atualmente ou não, para adotarmos dinâmicas e propostas de layout de acordo com a disponibilidade de informações dos candidatos. (Baseado em 2018).

### Critérios de aceite:

- [x] Mapeamento da base de dados do Perfil Político

**Comment by vanessa-nascimento** [comment]
https://docs.google.com/spreadsheets/d/1N0vD7gHk312HKHldR9KpwtB-mg1SnibPUZt-YVfIG6M/edit?usp=sharing
