### ISSUE TITLE
[Frontend] Criação de componentes

### ISSUE THREAD

**Issue by vanessa-nascimento** [okfn-brasil/perfil-politico-frontend#54]
Criação de componentes do projeto. Componentes são definidos como padrões que encontramos em nosso layout e partir disso criamos trechos de código que poderá ser reutilizável em toda aplicação, apenas chamando o "objeto". Assim, se houver uma alteração no componente, não precisará dar manutenção em vários lugares se o código que é a mesma coisa não for centralizado em um lugar. No novo design do Perfil Político temos os seguintes componentes:

- [x] Menu
- [x] Card do candidato
- [x] Card de gráficos e informações
- [x] Rodapé
- [x] Paginação
- [x] Logotipo
- [ ] Análises
- [x] Faq

**Comment by giuliocc** [comment]
Podemos colocar como parte da sprint 8, certo?
