### ISSUE TITLE
Eleições Municipais 2024

### ISSUE THREAD

**Issue by rousbound** [okfn-brasil/perfil-politico-frontend#73]
Olá a todos,

Gostaria de saber se temos alguma movimentação sobre esse ou algum outro projeto relacionado às Eleições Municipais de 2024.

**Comment by ogecece** [comment]
Olá, @rousbound !

Faremos um anúncio público em breve, mas já posso adiantar que  no momento não há recursos nem comunidade formada para atualizar o projeto para 2024.

Se quiser trocar mais ideias sobre como contribuir com esse projeto ou com outros, pode chegar lá no [Discord da OKBR](https://go.ok.org.br/discord).

Abraço!

**Comment by rasrbk** [comment]
Oi, @rousbound! 

Com relação a ações no âmbito das eleições municipais, temos um projeto chamado '[Carta-compromisso](https://embaixadoras.ok.org.br/civic%20tech/transpar%C3%AAncia/dados%20abertos/2020/11/05/carta-compromisso-por-municipios-mais-transparentes-e-colaborativos/)', onde buscamos fomentar o comprometimento de pessoas candidatas com uma gestão que priorize a transparência e a abertura de dados públicos. Estamos prevendo uma nova edição esse ano. Caso você tenha interesse, pode ficar de olho nas nossas redes sociais. Em breve divulgaremos mais informações! :)

**Comment by rousbound** [comment]
Olá @ogecece e @rasrbk!

Obrigado pelas respostas!

Aguardo o anúncio da comunidade sobre as eleições @ogecece.

E vou me atentar ao projeto Carta-Compromisso @rasrbk.

Abraços.
