### ISSUE TITLE
Fix toCurrency function

### ISSUE THREAD

**Issue by cuducos** [okfn-brasil/perfil-politico-frontend#9]
The function [`toCurrency`](https://github.com/okfn-brasil/perfil-politico-frontend/blob/2adfba365339e97aafb620236c1f36f8b531fd90/src/js/modules/mod-viz.js#L183-L186) is not behaving as expected because it strips zeros from the decimals:

<img width="427" alt="pasted_image_03_10_18_09_41" src="https://user-images.githubusercontent.com/4732915/46411269-b15ed400-c6f1-11e8-987f-6964ec3d5859.png">

**Comment by shahmk** [comment]
I can work on this

**Comment by honeyyenoh** [comment]
Hi, can I take this issue?

**Comment by cuducos** [comment]
Closed by #11
